site_name: CLIMB-TRE
site_url: https://climb-tre.github.io/
repo_url: https://github.com/CLIMB-TRE/climb-tre.github.io/
repo_name: CLIMB-TRE/climb-tre.github.io
site_author: CLIMB-TRE

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.top
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      timezone: Europe/London
      type: custom
      custom_format: "Last modified %Y-%m-%d %X %z"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: false
  - with-pdf:
      output_path: climb-tre.pdf
      cover_subtitle: ""
      debug_html: true
      show_anchors: true
      verbose: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting started:
    - Uploading data: upload.md
    - Analysing data: analyse.md
    - Further Examples:
      - Analysis examples for mSCAPE: mscape-examples.md
  - Project specifications:
    - Common structure: common.md
    - PATH-SAFE:
      - Uploader specification: pathsafe.md
      - Analysis specification: pathsafe-analysis.md
    - mSCAPE: 
      - Uploader specification: mscape.md
      - Analysis specification: mscape-analysis.md
  - Onyx-client: https://CLIMB-TRE.github.io/onyx-client/
